<a href="https://colab.research.google.com/github/lucifer-here/python-basic-programs/blob/main/basic_python_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#factorial of a number
def fact(num):
    if num==1:
      return num
    else:
      return num * fact(num-1)  #recursive function 

print(fact(3))
    

6


In [ ]:
#palindrome or not
def palindrome(num):
  x1=num[::-1]   #reversing the variable
  if x1==num:    #comparing whether it is equal to the original value 
    print("palindrome")
  else:
    print("not palindrome")


palindrome('madan')



not palindrome


In [ ]:
# Function for nth Fibonacci number
#function
def Fibonacci(n):

	# Check if input is 0 then it will
	# print incorrect input
	if n < 0:
		print("Incorrect input")

	# Check if n is 0
	# then it will return 0
	elif n == 0:
		return 0

	# Check if n is 1,2
	# it will return 1
	elif n == 1 or n == 2:
		return 1

	else:
		return Fibonacci(n-1) + Fibonacci(n-2)
#driver
print(Fibonacci(int(input("enter a number"))))







enter a number0
0


In [ ]:
#print fibbonacci series for n 

def fib(n):
  if n<0:
    return 0
  elif n==1:
    return 1
  else:
    return fib(n-2)+fib(n-1)
  

n=int(input("enter a number"))
for n in range(0,n):
  print(fib(n)," ")


enter a number10
0  
1  
1  
2  
3  
5  
8  
13  
21  
34  


In [ ]:
#amstrong number or not
#amstrong is a such that sum of cube of all its digits is equal to the same number
def isamstrong(num):
  s=0
  temp=num
  while temp>0:
    c=temp%10
    s += c**3
    temp//=10
  if num==s:
    print("amstrong")
  else:
    print("not amstrong")
  
num=int(input("enter a number"))
print(isamstrong(num))
   

enter a number351
not amstrong
None


In [ ]:
#calculator program
def add(a,b):
  return a+b
def subtract(a,b):
  return a-b
def multiply(a,b):
  return a*b
def divide(a,b):
  return a/b
def sqr(a,b):
  return a**b
def si(p,r,t):
  return (p*r*t)/100
def ci(p,r,t):
  return p* pow((1+r/100),t)


print(si(10000,10,5))
print(ci)

5000.0


In [ ]:
#pattern program
num=5
m=(2*num)-2
for i in range(0,num):
  for j in range(0,m):
    print(end="")# 
  m=m-1
  for j in range(0,i+1):
    print("*",end=' ')
  print(" ")

*  
* *  
* * *  
* * * *  
* * * * *  


In [ ]:
#leap year
#leap year has 29days in the month of feb and occurs every 4 years

year=int(input("enter a year"))
if year % 400==0:
   print("leap year")
if year % 4==0:
  print("leap year")
elif year %100==0:
  print("not a leap year")
else:
  print("not a leap year")

enter a year1900
leap year


In [ ]:
#prime number or not
def isprime(n):
  if n==1:
    print("neither a prime nor composite")
  else:
    for i in range(2,n):
        if n % i==0:
          print("not prime number")
          break
        else:
          print("prime number")
          break
        
n=int(input("enter a number"))
isprime(n)

enter a number1
neither a prime nor composite


In [ ]:
#area in python
import math #has the math functions
pi=math.pi
def circle(radius):
  return pi*(radius**2)
def cube(side):
  return side**2
def cylinder(radius,height):
  return  2*pi*radius + 2*pi*h
def sphere(radius):
  return 2*pi*(radius**2)


print(round(circle(4)))  #use round when ever you need to round off a number


50


In [ ]:
#python program to reverse a list


l=[1,2,3,4,5]
print(l[::-1])   #one way
l.reverse()      #another way using built in function
print(l)

[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


In [ ]:
#REMOVE ALL DUPLICATE ELEMENTS FROM LIST
list1=[1,2,1,2,5,7,8]
#list1=set(list1)   #using set #method 1
print(list1)
#or 
res=[]
for i in list1:    #method 2
  if i not in res:
        res.append(i)
print(res)

#there are many methods use the one you like :)

[1, 2, 1, 2, 5, 7, 8]
[1, 2, 5, 7, 8]


In [7]:
#printing table(multiplication)
num=int(input("enter a number: "))
last=int(input("till?: "))
for i in range(1,last+1):
  print(num,'x',i,'=',num*i)


enter a number: 12
till?: 10
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120


In [15]:
#global variables vs local variables(for understanding purpose)

x="hello world"#here x is global variable

def fun():
  y="hola" #here y is local variable
  print("hello"+x+y)
fun()

hellohello worldhola


In [21]:
#write a class for name and age(for understanding purpose)
class person:
  def __init__(self,name,age):
    self.name=name
    self.age=age
p1=person("akash","22")
print(p1.name) 
print(p1.age)

akash
22


In [35]:
#matrix operations using numpy
import numpy
x=numpy.array([[1,2,3],[3,4,6],[2,4,5]])
y=numpy.array([[3,4,4],[3,5,7],[3,6,7]])
print("add \n",numpy.add(x,y))
print("subtract \n",numpy.subtract(x,y))
print("multiply \n",numpy.multiply(x,y))
print("divide \n",numpy.divide(x,y))
print("dot \n",numpy.dot(x,y))
print("transpose \n",x.T)

#and so on



add 
 [[ 4  6  7]
 [ 6  9 13]
 [ 5 10 12]]
subtract 
 [[-2 -2 -1]
 [ 0 -1 -1]
 [-1 -2 -2]]
multiply 
 [[ 3  8 12]
 [ 9 20 42]
 [ 6 24 35]]
divide 
 [[0.33333333 0.5        0.75      ]
 [1.         0.8        0.85714286]
 [0.66666667 0.66666667 0.71428571]]
dot 
 [[18 32 39]
 [39 68 82]
 [33 58 71]]
transpose 
 [[1 3 2]
 [2 4 4]
 [3 6 5]]


In [42]:
#Bubble sort
def BubbleSort(list1):
  l=len(list1)
  for i in range(0,l-1):
    for j in range(l-1):
      if (list1[j]>list1[j+1]):
        temp=list1[i]
        list1[j]=list1[j+1]
        list1[j+1]=temp
  return list1


list1=[1,3,4,5,6,7,8]
print(BubbleSort(list1))

[1, 3, 4, 5, 6, 7, 8]


In [58]:
#sort using built in function for list
list1=[1,3,4,5,6,7,8]
list1.sort()
print("sort",list1)
#max built in function
print("max",max(list1))
#reverse built in function
list1.reverse()
print("reverse",list1)
#built in remove function
list1.remove(4)
print("remove",list1)
#built in index function
list1.index(3)
#append
list1.append(4)
print("append",list1)
#extend
list2=[1,23,4]
list1.extend(list2)
print("extend",list1)

#and so on..

sort [1, 3, 4, 5, 6, 7, 8]
max 8
reverse [8, 7, 6, 5, 4, 3, 1]
remove [8, 7, 6, 5, 3, 1]
append [8, 7, 6, 5, 3, 1, 4]
extend [8, 7, 6, 5, 3, 1, 4, 1, 23, 4]
